### ISSUE TITLE
예시 gif와 설명이 다릅니다

### ISSUE THREAD

**Issue by airman5573** [woowacourse/javascript-baseball-precourse#75]
실행결과 gif에는 `1스트라이크 1볼` 이 나오는반면 설명에서는 '스트라이크와 볼이 같이 있는 경우 **볼을 먼저쓰고**, 스트라이크를 쓴다.' 로 되어있습니다.
확인 바랍니다 :D

**Comment by ellynhan** [comment]
문의 결과 프로그래밍 요구사항에 적힌대로 "볼을 먼저 쓰고 스트라이크" 순으로 적으시면 된다고 합니다 :)

**Comment by ellynhan** [comment]
> 실행결과 gif에는 `1스트라이크 1볼` 이 나오는반면 설명에서는 '스트라이크와 볼이 같이 있는 경우 **볼을 먼저쓰고**, 스트라이크를 쓴다.' 로 되어있습니다. 확인 바랍니다 :D



> 실행결과 gif에는 `1스트라이크 1볼` 이 나오는반면 설명에서는 '스트라이크와 볼이 같이 있는 경우 **볼을 먼저쓰고**, 스트라이크를 쓴다.' 로 되어있습니다. 확인 바랍니다 :D

문의 결과 프로그래밍 요구사항에 적힌대로 "볼을 먼저 쓰고 스트라이크" 순으로 적으시면 된다고 합니다 :)

**Comment by ellynhan** [comment]
> 실행결과 gif에는 `1스트라이크 1볼` 이 나오는반면 설명에서는 '스트라이크와 볼이 같이 있는 경우 **볼을 먼저쓰고**, 스트라이크를 쓴다.' 로 되어있습니다. 확인 바랍니다 :D

문의 결과 프로그래밍 요구사항에 적힌대로 "볼을 먼저 쓰고 스트라이크" 순으로 적으시면 된다고 합니다 :)

**Comment by woowapark** [comment]
확인하여 수정 예정입니다, 
제보 감사합니다 :)
